### PR TITLE
[flutter_local_notifications] Fix dependency error in Flutter 1.22

### LINKED ISSUE #782: Because every version of flutter_driver from sdk depends on platform 3.0.0-nullsafety.1 and flutter_local_notifications depends on platform ^2.2.1, flutter_driver from sdk is forbidden. So, because flutter_local_notifications depends on flutter_driver any from sdk, version solving failed
**Describe the bug**

Flutter 1.22 (dev/master channel) breaks flutter_local_notifications due to the platform package dependency.

**To Reproduce**

1. `flutter channel dev && flutter upgrade`
2. `cd example/`
3. `flutter pub get`
4. See error below:
```
Because every version of flutter_driver from sdk depends on platform 3.0.0-nullsafety.1 and flutter_local_notifications depends on platform ^2.2.1, flutter_driver from sdk is forbidden.
So, because flutter_local_notifications depends on flutter_driver any from sdk, version solving failed.
```

**Expected behavior**

The package should work with all Flutter upgrades.

**Sample code to reproduce the problem**

You can reproduce this with the example app included in the library.

### PR DESCRIPTION
**Pull request by acoutts**
This PR fixes #782 by removing the direct dependency to `platform`.

Tested on:
* Flutter 1.22 [dev channel] - iOS / Android
* Flutter 1.20 [stable channel] - iOS / Android
* Flutter 1.12.13 - Android only. The included sample app cannot be built on iOS due to the Xcode project migration: https://flutter.dev/docs/development/ios-project-migration

### CODE REVIEW

**Review by MaikuB — CHANGES_REQUESTED** [review]
Looks good but can you revert the change to `flutter_local_notifications/example/ios/Runner.xcodeproj/project.pbxproj` since it's not relevant for this PR and in case it causes an issue like the migration did?

**Comment by acoutts** [comment]
> Looks good but can you revert the change to `flutter_local_notifications/example/ios/Runner.xcodeproj/project.pbxproj` since it's not relevant for this PR and in case it causes an issue like the migration did?

Fixed!

**Review by MaikuB — APPROVED** [review]

**Comment by MaikuB** [comment]
Oops looks like i'll need to revert this, this is failing package validation that I can't even publish it...

**Comment by acoutts** [comment]
Oops! What did the error say? Is it something I can fix and re-submit?

**Comment by MaikuB** [comment]
It says

```
Package validation found the following error:
* line 6, column 1 of lib/src/flutter_local_notifications_plugin.dart: This package does not have platform in the `dependencies` section of `pubspec.yaml`.
    ╷
  6 │ import 'package:platform/platform.dart';
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
Package validation found the following potential issue:
* line 7, column 1 of test/platform_flutter_local_notifications_test.dart: This package does not have platform in the `dependencies` section of `pubspec.yaml`.
    ╷
  7 │ import 'package:platform/platform.dart';
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
Sorry, your package is missing a requirement and can't be published yet.
```

Not something I think you can fix. Also I just realised that issue you raised before is for a pre-release version of the `platform` package so I'm going to leave it in the reverted state. I'd suggest you use your fork in the meantime or see if you can use a dependency override in your own app as I'd rather not have the plugin depend on a pre-release version of a plugin as a solution

**Comment by acoutts** [comment]
Ah I see. In that case you're right, best we wait for the Flutter team to get things more ready. This release has been difficult for other packages too because of this platform dependency issue.

**Comment by acoutts** [comment]
Looks like there is a bug in android now on this new version as well and I can't show any notifications suddenly. This update will need a closer look.

```
E/MethodChannel#dexterous.com/flutter/local_notifications(24534): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications(24534): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications(24534): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:188)
E/MethodChannel#dexterous.com/flutter/local_notifications(24534): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:146)
E/MethodChannel#dexterous.com/flutter/local_notifications(24534): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:688)
E/MethodChannel#dexterous.com/flutter/local_notifications(24534): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:827)
E/MethodChannel#dexterous.com/flutter/local_notifications(24534): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:750)
E/MethodChannel#dexterous.com/flutter/local_notifications(24534): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#dexterous.com/flutter/local_notifications(24534): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#dexterous.com/flutter/local_notifications(24534): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#dexterous.com/flutter/local_notifications(24534): 	at android.os.MessageQueue.nativePollOnce(Native Method)
```

**Comment by acoutts** [comment]
Interestingly it only affects running on a physical device (pixel 4). Same app in a simulator doesn't have the error.

**Comment by acoutts** [comment]
Ah - the issue was I had a logic error and I wasn't actually calling `initialize()`, so there was no default icon for it to use. All set now!

**Pull request merged**
