### PR TITLE
[flutter_location_notifications] Add fullscreen support for android

### PR DESCRIPTION
**Pull request by klitzouille**
This is my first pull request ever, I don't know if I missed anything, but let met know if it's the case.

I updated the following files : 
- lib/src/platform_specifics/android/notification_details.dart to add support for fullscreen param
- android/src/main/java/com/dexterous/flutterlocalnotifications/models/NotificationDetails.java to reflect new dart param
- android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java to add fullscreen behaviour

### CODE REVIEW

**Comment by MaikuB** [comment]
I won't get to take a closer look yet but could do the following

- as this is a new feature and not but fix, can you see you change the target branch so that the PR is submitted to the `time_zone_macos_support`. The current beta release is done from that branch. As Would reduce overhead where new features get added to master, released and then I need to look at updating the beta release as well
- update the example app to demonstrate this feature
- make sure all tests are pass

**Comment by klitzouille** [comment]
Changing the target branch seems to have broken a lot of things. Should I also restart my devs from the time_zone_macos_support branch instead of master as well ?

**Comment by MaikuB** [comment]
That's probably the easiest option otherwise you'll need to deal with merging

**Comment by klitzouille** [comment]
Ok, thanks. I'll close this PR and reopen and everything is working properly.

**Comment by MaikuB** [comment]
Forgot to add a tip that I learnt recently. Instead of using master branch in your fork for your work, create another branch and use that as the one for submitting your PR. Makes it easier to keep your fork up to date

**Comment by klitzouille** [comment]
How stable is the time_zone_macos_support branch ? I noticed it uses the **extension-methods** experiment, and was wondering if I should stick to my "custom" master branch for my personnal project

**Comment by MaikuB** [comment]
Extension methods aren't experimental. If you're seeing that warning then you either have an out of date Flutter installation or issue with the analysis server. They were added in Dart 2.7 towards the end of last year

**Comment by klitzouille** [comment]
I'm not seeing any warning, but for the time_zone_... branch to work I had to add an analysis_options.yaml file with the following : 

analyzer:
  enable-experiment:
    - extension-methods

Which led me to believe that this was experimental.

**Comment by klitzouille** [comment]
Anyway, I cannot get the example working with Navigator.push in the onSelectNotification callback. It's only working when using runApp, and I don't have any clue on where to begin to fix it.

**Comment by MaikuB** [comment]
I don't know either but maybe best to start with checking which version of Flutter you have installed given the issue you had with extension methods. You can check that by running `flutter doctor -v`

**Comment by niteshgrg** [comment]
@MaikuB wandering was there another PR for this feature ? Is currently full screen notification via this plugin supported ?

**Pull request closed without merging**
