### PR TITLE
[flutter_local_notifications] Android 12 support

### PR DESCRIPTION
**Pull request by MaikuB**
Relates to #1171 

Has changes required for apps targeting Android 12. As Android 12 is still in beta, this PR will remain open until stable release and any related changes made to the plugin for Android 12 will got out as a pre-release until then

### CODE REVIEW

**Comment by nstrelow** [comment]
Would be great if this could make it into a pre release again 😁

**Comment by MaikuB** [comment]
Not sure what you mean but the prerelease still exists. It's just that the 7.0.0 release was an emergency one so differs from what was in 7.0.0 prerelease. You can also point to a git branch in your pubspec

**Comment by nstrelow** [comment]
@MaikuB Thanks for your reply. Yes I am pointing now to dev.2, which is with Android 12 and working on web.

Had to override the flutter_local_notifications_platform_interface to 4.0.0, because the required changes for 4.0.1 are not in dev.2

Basically I use Android 12 and Flutter web

**Comment by MaikuB** [comment]
Closing in favour of https://github.com/MaikuB/flutter_local_notifications/pull/1268

**Pull request closed without merging**
