### PR TITLE
#140 Fixed an issue that is immediately notified on devices before iOS 10

### PR DESCRIPTION
**Pull request by ganessaa**
We confirmed that the values change on both flutter side and Objective-C side. For that reason, we passed it as a character string from flutter and changed it to analyze as longLongValue.

We feel that we need to make similar modifications in `scheduledDate.millisecondsSinceEpoch` used for other uses.(We have not done it.)

### CODE REVIEW

**Comment by ganessaa** [comment]
We can not remove flutter's `toString()`. The value is also truncated between flutter and Objective-C. We avoided it by passing that value as a string.

We can not remove codes on both flutter side and Objective-C side. Both of them are truncated.

(Perhaps the problem between flutter and Objective-C should be fixed without using strings in the original flutter project.)

**Comment by MaikuB** [comment]
To be clear what I'm referring to is to remove the toString on Flutter but keep the objective C code to parse the value as a long. Has that been tried? I think the truncation is to do with how it use to parse it as an integer

**Comment by ganessaa** [comment]
We can not erase toString() on Flutter side.
We already checked the following values.

flutter_local_notifications.dart
```
print(scheduledDate.millisecondsSinceEpoch);
```

FlutterLocalNotificationsPlugin.m
```
NSLog(@"%@" , call.arguments[MILLISECONDS_SINCE_EPOCH]);
NSLog(@"%ld" , [call.arguments[MILLISECONDS_SINCE_EPOCH] longLongValue] / 1000);
NSLog(@"%@" , @([call.arguments[MILLISECONDS_SINCE_EPOCH] longLongValue] / 1000));
```

Logs without toString()
```
1545269441429
```
```
-918785131
-918785
-918785
```

Logs with toString()
```
1545269975724
```
```
1545269975724
1545269975
1545269975
```

As we are not English native speakers, we may be misunderstanding your question.
Does this information satisfy you?

**Comment by MaikuB** [comment]
That answers the question. Thanks

**Comment by ganessaa** [comment]
=)

**Comment by MaikuB** [comment]
Have you checked android? The changes made in Flutter to pass a string would mean changes are required on the Android side when parsing the values

**Comment by ganessaa** [comment]
Ah! You are right.
We have to check on Android.
We will tell about result later.

**Comment by ganessaa** [comment]
We were not used to creating plugins and our request did not work correctly on Android.
We withdraw the request.

**Pull request closed without merging**
