### PR TITLE
Implement exact and allow while idle options for android

### PR DESCRIPTION
**Pull request by alexandr2levin**
It isn't final implementation. @MaikuB, do you like the idea?

### CODE REVIEW

**Comment by alexandr2levin** [comment]
https://github.com/MaikuB/flutter_local_notifications/issues/216

**Comment by MaikuB** [comment]
Thanks for attempting this. Just a note first that you should be able to create a draft PR to discuss with others.

My thoughts on this were to create something like a `ScheduledNotificationDetails` class that extends from the Android-specific `NotificationDetails` one and it would have a property that describes the behaviour. This could be an enum called something like `ScheduledNotificationTiming` with the following possible values


- Exact
- ExactAndAllowWhileIdle (this should probably be the default)
- Inexact
- InexactAndAllowWhileIdle


You currently have two booleans, which means one can be toggled without the other on but they are related to each other. The enum would help depict that relationship a lot more clearer, clarify what the behaviour and make it easier for devs to use.

The schedule method would be updated to take an instance of the `ScheduledNotificationDetails` class. That way the `repeat` method can be left as it was before and can be revisited later

**Comment by MaikuB** [comment]
Do you plan to make more changes based on my reply?

**Comment by MaikuB** [comment]
Closing this due to lack of further response and will use #256 to continue work on this. Thanks again for attempting this though

**Pull request closed without merging**
