### PR TITLE
[flutter_local_notifications] fixed an issue with null schedule mode for older notifications scheduled using periodicallyShow on Android

### PR DESCRIPTION
**Pull request by MaikuB**
Relates to #2033

### CODE REVIEW

**Comment by nohli** [comment]
Thanks for the fix!

I don't know how to test it properly though?
It gladly only affects a few users.

**Comment by MaikuB** [comment]
When you say you don't know how to fix, by that do you mean you don't know how to reproduce these issue or that you don't know how to update your app to point to the branch referenced by this PR?

**Comment by nohli** [comment]
Don't know how to reproduce the issue, as it happens for <0.001% of users (with daily notifications).

**Comment by MaikuB** [comment]
Based on the trace you shared before, it indicates to me that you have an app that has used version 1.x of this plugin and calls the `periodicallyShow()` method as the `androidAllowWhileIdle` parameter was added in 2.0. The issue happens as the changes done as part of https://github.com/MaikuB/flutter_local_notifications/pull/1881 didn't seem to account for this and is similar to the #2033 but for a different method provided by the plugin

**Comment by nohli** [comment]
Oh, interesting. You mean, the users who experience this crash use the app for about 3 years, where it used plugin version <2? That would explain why the exception is so rare.

It's a bit hard to roll back the system to a state of 3 years ago, isn't it? I can try to downgrade Flutter etc., checkout an old commit, install the app, and then revert everything, install again and see if the crash happens.

But the app calls `cancelAll()` on a fresh app start and reschedules all notifications. Could it still cause this error?

On a side note, one user reported that he can't cancel a daily notification. His workaround is to disable notifications from the app's `channelId` in system settings. Could it be that it's him having the exceptions, and for some reason the plugin can't cancel very old notifications, which then cause this exception?
The app regularly calls `cancelAll()` and reschedules all notifications. Users can see their notifications (which get rescheduled after cancelling), and he reported the notification doesn't show up in the list.

**Comment by MaikuB** [comment]
> It's a bit hard to roll back the system to a state of 3 years ago, isn't it? I can try to downgrade Flutter etc., checkout an old commit, install the app, and then revert everything, install again and see if the crash happens

Yeah it could be quite hard to roll back. May have to simulate by modifying the code so that the JSON representing the notification saved to shared preferences is same as what would get saved from version 1.x

> But the app calls cancelAll() on a fresh app start and reschedules all notifications. Could it still cause this error?

It should but perhaps there are users who haven't started another session?

> On a side note, one user reported that he can't cancel a daily notification. His workaround is to disable notifications from the app's channelId in system settings. Could it be that it's him having the exceptions, and for some reason the plugin can't cancel very old notifications, which then cause this exception?

I'm doubtful as I've seen a correlation between a channel and cancellation. Should be something that can be verified easily though

**Comment by MaikuB** [comment]
@nohli FYI this has been released as part of 16.0.0-dev.2, 15.1.1 and 14.1.3

**Comment by nohli** [comment]
> @nohli FYI this has been released as part of 16.0.0-dev.2, 15.1.1 and 14.1.3

Wow thank you so much!! ❤️

**Comment by nohli** [comment]
15.1.1 is not yet available on pub.dev.

**Comment by MaikuB** [comment]
Hmm thought I published it. Perhaps I forgot to hit the button. Hang on

**Comment by MaikuB** [comment]
Ok done now. Got mixed up with when I pushed out 14.1.3+1

**Comment by nohli** [comment]
Your support is really amazing! ❤️

Still can't see 15.1.1 nor 14.1.3 though 🙈

**Comment by MaikuB** [comment]
I forgot to bump the version in pubspec.yaml file that I missed publishing failed. It's done but you have to go to versions tab to see 14.1.3

image

**Comment by nohli** [comment]
Great, 15.1.1 is live, thank you again 😊

**Comment by nohli** [comment]
FYI no crashes with the latest version 🙏🏽

**Pull request merged**
