### PR TITLE
 [flutter_local_notifications] Bulk sheduling

### PR DESCRIPTION
**Pull request by hurrba**
Refactored to make it possible to bulk schedule notifications. 

**Related issue:** 
#459

### CODE REVIEW

**Comment by MaikuB** [comment]
Thanks for the PR. I'll look at it more in depth later in the week. Other thing is if I look at merging it in, I'll probably do so after solving the timezone issues with scheduling that I believe I have a solution for now where I'll likely deprecate the old methods.

**Comment by MaikuB** [comment]
Took a look and I'm going to hold off on this to make the timezone changes I mentioned. There are other changes I'd like to see done as well and can left till then. Not sure if you'd prefer to leave this open until then or I can close this for now for revisiting later

**Comment by hurrba** [comment]
Thank you for taking the time. You can just close it for now

**Comment by MaikuB** [comment]
Sure

**Comment by serikshaikamalov** [comment]
Can you merge this PR please. I would be grateful

**Pull request closed without merging**
