### PR TITLE
[flutter_local_notifications] Fixes #1486 :Adds ability to count down chronometer with chronometerCountDown

### LINKED ISSUE #1486: Timer in notification
Can I with this package leave a timer running on the notification like the android's native timer?
And when accessing the notification, open the app at the time set in the notification timer?

### PR DESCRIPTION
**Pull request by ebelevics**
Fixes https://github.com/MaikuB/flutter_local_notifications/issues/1486, https://github.com/MaikuB/flutter_local_notifications/issues/791, https://github.com/MaikuB/flutter_local_notifications/issues/306

**chronometerCountDown** will only work for Android devices that are 7.0 or newer. But this will do the trick for updating timer without updating notification every single second.
```dart
AndroidNotificationDetails(
          _channelKey,
          'Channel',
          channelDescription: 'Description',
          when: endAt.millisecondsSinceEpoch, // should be greater than DateTime.now()
          timeoutAfter: endAt.difference(DateTime.now()).inMilliseconds, // this will ensure that notification will hide after reaching 0:00
          usesChronometer: true,
          chronometerCountDown: true, // chronometer will go backwards from positive to negative
        ),
```

### CODE REVIEW

**Comment by ebelevics** [comment]
Noticed typo at notification_details.dart. Should be `/// This property is only applicable to Android 7.0 and newer versions.`

**Comment by MaikuB** [comment]
Thanks for the PR. Could you push an update to fix the issue in the API docs that you had mentioned in your previous message?

**Comment by ebelevics** [comment]
Api doc corrected

**Comment by MaikuB** [comment]
Thanks for the update. The unit tests are failing due to the updates made in this PR, could you look to address this as well?

**Comment by ebelevics** [comment]
Sorry for delay, done.

**Pull request merged**
