### PR TITLE
[flutter_local_notifications] Added callback for dismissing a notification

### PR DESCRIPTION
**Pull request by matanshukry**
Notes:
- I don't have a Mac so this is an Android only version. I hope the iOS version will be not be complex either
- I couldn't think of a way to show the dismiss in the UI, so right now you can just see it in the console
  - I thought about using a Snackbar but there isn't a scaffold, and I wasn't sure it's worth adding

### CODE REVIEW

**Comment by MaikuB** [comment]
Your PR only works when the app is actually running and is why I haven't implemented it myself. The reason why #74 was marked as blocked and is mentioned in the thread that it should also when the app isn't running via headless Dart execution.  This is something that has issues at the moment and I'm not looking to merge such changes until it works in that scenario unless the Flutter team decides not to support headless execution anymore. This is something that was being discussed amongst the team to from what I know

**Comment by matanshukry** [comment]
@MaikuB One could implement it in a service, much like FCM does.
Or the issues you're talking about also apply there? If so, what issues are those?

**Comment by MaikuB** [comment]
Also applies to FCM and same reason why #17 is blocked, which goes to this issue I raised on the Flutter repo itself https://github.com/flutter/flutter/issues/23904

**Comment by matanshukry** [comment]
@MaikuB Would you care to explain how does it apply to FCM exactly?
A quick test on my app that uses FCM seems to work:

1. Sending message when app is in the foreground (works)
2. Terminating the app
3. Sending message when app is terminated (works, and launches the app)
4. Sending message when app is in the foreground (works)

The repo you provided in the flutter issue isn't valid anymore, so at least that is what I understood from your explanation.
Correct me if I'm wrong.

**Comment by MaikuB** [comment]
Actually, I forgot FCM has different callbacks for different scenarios. In that case it _might_ not be an issue as they appear to detect if the app is running or not. Though if you look at the [last comment](https://github.com/flutter/flutter/issues/23904#issuecomment-652148410), you can see another user being impacted by the issue where once background execution works, it stops normal callbacks from working

> The repo you provided in the flutter issue isn't valid anymore, so at least that is what I understood from your explanation.

I'm not sure what point you were trying to make here. What I meant there is that I accidentally deleted the repository that demonstrates the problem that still exists. Perhaps you confused repo with repro steps? The issue

**Comment by matanshukry** [comment]
> I'm not sure what point you were trying to make here. What I meant there is that I accidentally deleted the repository that demonstrates the problem that still exists. Perhaps you confused repo with repro steps? The issue

I meant I didn't fully understand the context since I couldn't read the code, so I might of missed something.

> Though if you look at the last comment, you can see another user being impacted by the issue where once background execution works, it stops normal callbacks from working

I did see it, but I'm using FCM with many other plugins (and channels) and never encountered such an issue, nor have I read about it somewhere. If it is a bug it seems rare enough that it could be ignored (at least in my case).

> In that case it might not be an issue as they appear to detect if the app is running or not
Assuming I implement it like they did then, and it would work in the background - will you accept it into this plugin?

Keep in mind I can't implement the iOS side.

**Comment by MaikuB** [comment]
> Assuming I implement it like they did then, and it would work in the background - will you accept it into this plugin?

Not looking to at this stage as the related issue is still an issue. It also adds maintenance burden where I need to consider what the migration path would be when general background execution land as callbacks need to be saved in shared preferences at the moment. PR would need an iOS and macOS implementation (I added support to macOS in a prerelease version)

If you what you have works for you then I'd suggest you keep your own fork going. Would be interested in seeing how it goes, particularly to see if you run into issues

**Comment by matanshukry** [comment]
@MaikuB I completed the fork and the changes and it's now working correctly. Feel free to take a look and comment, would love to hear your opinion.

Also, regarding the last comment in the Dart PR - I've encountered the issue as well, but it seems to be an issue with FCM specifically. there is also a PR that fixes it, although it's not in. Thought you might be interested to know that:
https://github.com/FirebaseExtended/flutterfire/pull/1917

**Comment by pranavo72bex** [comment]
Any Update regarding this PR?

**Pull request closed without merging**
